# Generated by Django 5.2.5 on 2025-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
